### ISSUE TITLE
Recordings have no extension on computer

### ISSUE THREAD

**Issue by john7777777** [mentaljam/sailfish-recorder#10]
I connected my jolla sailfish to the computer to download the recordings I made with this recorder, but the files had no extension and i cant load them into my audio program. I tried adding a .mp3 and a .wav, but the files still wouldnt load. I can still listento the files fine on my jolla, so the data is still intact. How do i get it into a regular audio format?

UPDATE:  I did not rename the file on my phone, I copied them from my phone to the computer, but did not change the original files on the phone.

**Comment by cornedor** [comment]
Sorry for the late response, was away on holiday. 
What codec have you set in the settings? And have you even changed it?

**Comment by mentaljam** [comment]
Seems to be fixed in old commits. Please, re-open the issue if it is still actual.
