### ISSUE TITLE
Implement Share functionality

### ISSUE THREAD

**Issue by lkraav** [mentaljam/sailfish-recorder#11]
Would be nice to e-mail, bluetooth, etc the recordings around.

**Comment by cornedor** [comment]
I've a seperate branch with share functionality, but the harbour store doesn't allow the use of the API's i've used, I will still keep this issue open, it might have changed by now, so if I have some time left i'll look into it.

**Comment by mentaljam** [comment]
Recorder with share functionality is now available on OpenRepos.
