### ISSUE TITLE
Update version in the Jolla Store

### ISSUE THREAD

**Issue by mentaljam** [mentaljam/sailfish-recorder#18]
@cornedor could you please update recorder in the official Jolla Store or maybe we can try to transfer its ownership so I can update recorder by myself?

Here is the [discussion](https://openrepos.net/comment/32086#comment-32086) on OpenRepos.

**Comment by cornedor** [comment]
Hey, transfering the ownership to you would be a good solution, i'll try to contact Jolla.

**Comment by sebix** [comment]
Has there been a progress on this? I'm curious because the openrepos version has various improvements by @mentaljam and added translations :)

**Comment by mentaljam** [comment]
The ownership was successfully transferred
