### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by sebix** [mentaljam/sailfish-recorder#20]
Hi,

at transifex I translated the app to German. Could this please be included? Thanks! Although the README in the translations directory helps a bit, I could not find out how to get the .ts file to be included in the repo.

Thank you for this nice app!

**Comment by wagner-certat** [comment]
Thank you!

**Comment by sebix** [comment]
Thank you!

**Comment by mentaljam** [comment]
Thank you!
I include new files from Transifex manually after they are finished.
By the way, give thanks better to @cornedor :)
